/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.my;

import java.util.logging.Logger;

public class App {
	private static final Logger LOG = Logger.getLogger(App.class.getName()); 
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String greeting = new App().getGreeting();
		System.out.println(greeting);
        LOG.info(greeting);
    }
}
